services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"  # Map port 5001 on host to port 5001 in the container
    volumes:
      - ./backend:/app  # Mount the backend directory to the container
    env_file:
      - ./backend/.env  # Load environment variables from .env file
    environment:
      - FLASK_ENV=development  # Set Flask to development mode for auto-reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:80"  # Map port 5000 on host to port 80 in the container
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html  # Mount the index.html to the container

  mongodb:
    image: mongo:latest  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Map MongoDB default port to host
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data in a Docker volume

volumes:
  mongo_data:  # Define a volume for MongoDB data persistence
